### ISSUE TITLE
Change UID and GID variables to ENV instead of ARG ?

### ISSUE THREAD

**Issue by venkatnsrinivasan** [blacklabelops/jira#101]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem.
    * Checked that your issue isn't already filed.
    * Filled the form.
    * Included logs and system information.

### Description

Is it possible to change the 

ARG CONTAINER_UID=1000
ARG CONTAINER_GID=1000 

to be environment variables so that we can use the parent image from dockerhub and pass the UID and GID as environment variables instead of using the Dockerfile in github directly ?
I can make a fork/copy and try but didnt want to maintain seperate versions

Thanks

**Comment by blacklabelops** [comment]
I do not think the ARGs actually work because it's already overwritten in line 65 of the Dockerfile. 

The whole issue is doable but just rather challenging as the ARG user is already used inside the Dockerfile. I do not know if you can adjust the jira user after the Jira installation. Also, you would have to reown stuff each time the container is started, which is rather dirty.

You can make a fork/copy and afterwards do a pull request. After a proper review you do not have to maintain separate versions.

For example I would like a proper implementation expect to behave in an idempotent manner, means:

* Files should not be reowned each time but there should be a proper routine that expertly decides a reown is required.

Downwards Compatibility for people already using the image:

* Must be activated, default behavior must be the current entrypoint behavior with default user.

**Comment by venkatnsrinivasan** [comment]
Ok, let me think about it. Right now Iam trying to migrate our existing applications to docker from a server env and using host path volumes to use the existing home directories but the 1000 uid maps to a random user in our system making all the permissions off. Trying to find a solution for that.

Thanks
