### ISSUE TITLE
Could not create connection to database server.

### ISSUE THREAD

**Issue by SydOps** [blacklabelops/jira#2]
@blacklabelops 

I'd like to connect mysql via official mysql container with below code: 
```
docker run -d --name mysql \
  -e 'MYSQL_ROOT_PASSWORD=pass1234' \
  -e 'MYSQL_DATABASE=jiradb' \
  -e 'MYSQL_USER=jiradb' \
  -e 'MYSQL_PASSWORD=jellyfish' \
  -p 3306:3306 \
  mysql:5.7.7
```
But after run jira container
```
docker run -d --name jira \
    -e "DATABASE_URL=mysql://jiradb@mysql/jiradb" \
    -e "DB_PASSWORD=jellyfish"  \
    --link mysql:mysql \
    -p 8100:8080 \
    blacklabelops/jira
```
I got error:

>2015-08-02 04:59:08,972 localhost-startStop-1 ERROR      [NoModule] Error getting datasource via DBCP: JdbcDatasourceInfo{uri='jdbc:mysql://mysql:3306/jiradb?autoReconnect=true&characterEncoding=utf8&useUnicode=true&sessionVariables=storage_engine%3DInnoDB', driverClassName='com.mysql.jdbc.Driver', username='jiradb', password='********', isolationLevel='null', connectionProperties=null, connectionPoolInfo=ConnectionPoolInfo{maxSize=20, minSize=20, initialSize=null, maxIdle=20, maxWait=30000, sleepTime=300000, lifeTime=600000, deadLockMaxWait=600000, deadLockRetryWait=10000, validationQuery=null, minEvictableTimeMillis=null, timeBetweenEvictionRunsMillis=null, poolPreparedStatements=null, testOnBorrow=null, testOnReturn=null, testWhileIdle=null, maxOpenPreparedStatements=null, numTestsPerEvictionRun=null, removeAbandonedTimeout=300, validationQueryTimeout=null, defaultCatalog=null}}
org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Could not create connection to database server. Attempted reconnect 3 times. Giving up.)
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1549)

Can you help?

**Comment by blacklabelops** [comment]
Hello Bill,

Thanks for asking. The Jira container does not work with the container mysql:5.7.7. There is something fishy about its basic setup. I guess the connection properties are too restrictive or the user and user privileges are not configured correctly.

That’s why i switched to tutum/mysql. It’s still working fine with that container. Please use the container from my tutorial. Tutum is a big startup Docker host provider, so I think you can trust those containers.

In order to compare both containers you will have to compare both Dockerfiles and Entrypoints. 

Best regards,
Steffen

**Comment by SydOps** [comment]
thanks.

**Comment by SydOps** [comment]
After used your code (both mysql and jira), I got same error. My environment is `Vagrant + CoreOS with latest vagrant box updated`.

>2015-08-02 09:46:15,625 localhost-startStop-1 ERROR      [NoModule] Error getting datasource via DBCP: JdbcDatasourceInfo{uri='jdbc:mysql://mysql:3306/jiradb?autoReconnect=true&characterEncoding=utf8&useUnicode=true&sessionVariables=storage_engine%3DInnoDB', driverClassName='com.mysql.jdbc.Driver', username='jiradb', password='********', isolationLevel='null', connectionProperties=null, connectionPoolInfo=ConnectionPoolInfo{maxSize=20, minSize=20, initialSize=null, maxIdle=20, maxWait=30000, sleepTime=300000, lifeTime=600000, deadLockMaxWait=600000, deadLockRetryWait=10000, validationQuery=null, minEvictableTimeMillis=null, timeBetweenEvictionRunsMillis=null, poolPreparedStatements=null, testOnBorrow=null, testOnReturn=null, testWhileIdle=null, maxOpenPreparedStatements=null, numTestsPerEvictionRun=null, removeAbandonedTimeout=300, validationQueryTimeout=null, defaultCatalog=null}}
org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Could not create connection to database server. Attempted reconnect 3 times. Giving up.)

I can make sure the mysql database runs well
```
$ docker run -it --link mysql:mysql --rm tutum/mysql:5.6 sh -c 'exec mysql -h"$MYSQL_POR3306_TCP_ADDR" -P"$MYSQL_PORT_3306_TCP_PORT" -u"$MYSQL_ENV_MYSQL_USER" -p"$MYSQL_ENV_MYSQL_PASS"'
Warning: Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 5
Server version: 5.6.19-0ubuntu0.14.04.1 (Ubuntu)

Copyright (c) 2000, 2014, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> exit
Bye
```

**Comment by blacklabelops** [comment]
Hello Quick Feedback: There is a Vagranfile inside my project. Please try again inside that Vagrant machine because I have just checked my tutorial and it's working. I would like you to confirm that.

___ Database Configuration _________________

     Loading entityengine.xml from                 : file:/opt/jira/atlassian-jira/WEB-INF/classes/entityengine.xml
     Entity model field type name                  : mysql
     Entity model schema name                      : 
     Database Version                              : MySQL - 5.6.19-0ubuntu0.14.04.1
     Database Driver                               : MySQL Connector Java - mysql-connector-java-5.1.30 ( Revision: alexander.soklakov@oracle.com-20140310090514-8xt1yoht5ksg2e7c )
     Database URL                                  : jdbc:mysql://mysql:3306/jiradb?autoReconnect=true&characterEncoding=utf8&useUnicode=true&sessionVariables=storage_engine%3DInnoDB
     Database JDBC config                          : mysql jdbc:mysql://mysql:3306/jiradb?autoReconnect=true&characterEncoding=utf8&useUnicode=true&sessionVariables=storage_engine%3DInnoDB

2015-08-02 10:15:03,352 localhost-startStop-1 INFO      [atlassian.jira.startup.ClusteringChecklistLauncher] JIRA clustering startup checks completed successfully.
2015-08-02 10:15:03,369 localhost-startStop-1 INFO      [atlassian.jira.startup.JiraStartupLogger] 

___ Starting the JIRA Plugin System _________________

**Comment by SydOps** [comment]
Thanks @blacklabelops . I test in boot2docker, it runs fine.  I am still downloading the box `blacklabelops/dockerdev`, which need another 40 minutes, will confirm with you later if it runs well or not.

By the way, I run the docker and have this issue in CoreOS (git clone https://github.com/coreos/coreos-vagrant.git). Docker should be content agnostic, not sure why have different result.

**Comment by SydOps** [comment]
my updates:

1. jira+mysql:
works with your vagrant box and boot2docker, but didn't work in Vagrant + latest CoreOS 

2. jira+postgresql:
all fine.

The error I have is related the jdbc connector driver. Check in your image and container, the jdbc file `mysql-connector-java-5.1.36-bin.jar` should be in /opt/jira/lib, but I didn't find it , and not sure, how this works with your vagrant box

**Comment by blacklabelops** [comment]
Hello Bill,

It is a network problem. The mysql-connector is downloaded during installation. So container to container communication and container to outside world communication does not work on your installation. I assume that inside your installation Docker is not able to start a network adapter. Also there is the possibility that your firewall, especially firewalld, is blocking docker communication. 

Normally Docker manipulates iptables in order to allow communication but CentOS 7 uses firewalld. My dockerdev has firewall disabled but it's built daily with latest kernel and packages.

Please check your vagrant box for a firewall and apply a tutorial on how to setup docker with firewalld.

Best regards,
Steffen

**Comment by SydOps** [comment]
I run with postgresql to avoid this issue. No time to wait. Ticket can be closed.
