### ISSUE TITLE
Immutable Images - Daily new tag builds

### ISSUE THREAD

**Issue by Firefishy** [blacklabelops/jira#51]
The versioned tags are changing SHA1 daily.

This is unfriendly to SWARM clusters (and similar) which lock hash + tag version, but then are not able to download the container image the next day to a new swarm host because the hash has changed.

The build process should be improved to only rebuild when necessary.

**Comment by Firefishy** [comment]
I am somewhat unsure how the images are built. I am happy to create a proof-of-concept build system based on docker-compose which only builds when tag or upstream change.

**Comment by blacklabelops** [comment]
This repository is using Push-CI-Builds with CircleCI.

Buildfile is here: https://github.com/blacklabelops/jira/tree/master/.circleci

My other repositories Confluence, Crowd, Bitbucket are Jenkins built.

**Comment by blacklabelops** [comment]
Hey Firefishy,

In my opinion this is a matter of maintenance rather specific buildscripts. 

- Something like release branches which need to be maintained but can be released independent of each other.

- Push button releases for fixed release vs. continuous build for latest image.

- Enhanced versioning: Adding build number to fixed tagged images.

Something I am avoiding because of the work connected to it. If you would like to help me maintaining the releases then I would be glad to add you with additional privileges on this repository.

**Comment by blacklabelops** [comment]
I would like to keep my daily builds. For swarm users I could offer manual push releases where I add a build number to the version number. These images could be released manually or once each month.

**Comment by Firefishy** [comment]
Not to worry, I have a workaround. I use the following to ensure the tagged + hashed container is available across all the hosts that might run the image in the future: docker-compose.yml
```
  confluencesleeper:
    image: "blacklabelops/confluence:6.5.2"
    command: sleep 604800
    deploy:
      mode: global
      restart_policy:
        condition: any
```
