### ISSUE TITLE
Jira upgrade path using immutable docker containers

### ISSUE THREAD

**Issue by esciara** [blacklabelops/jira#64]
Hi there,

I am trying to figure out the correct upgrade path when using immutable Jira containers... I could not find much so far, the most complete description I could find being https://github.com/cptactionhank/docker-atlassian-jira/issues/3 .

The problem with the description is that it does not seem to be foolproof, especially when upgrading to major upgrades (e.g. 6.x.x => 7.x.x), and that it does not mention how to deal with installed add-ons.

Any information/opinion/links on the subject?

Em

**Comment by esciara** [comment]
Here is another reference for the record: https://github.com/cptactionhank/docker-atlassian-jira/issues/39

**Comment by blacklabelops** [comment]
This is a good question. Of course I will describe this workflow in more detail with blacklabelops images, example commands and personal experience. At the moment i can give you the following advice; you should always follow the following basic workflow for all upgrades:

1. Backup
2. Upgrade
3.  Test

Depending on the test result: Rollout or Rollback!

I guess that's basically the workflow described by cptactionhank.

Dependent on your local setup, backup solution and environments this workflow may differ.

More details will follow shortly!

**Comment by blacklabelops** [comment]
More detailed version, feel free to comment in order to improve the description! This description is without any guarantee as this procedure may get outdated or omit critical details which may lead to data loss. Use at own risk. 

Before you take any action make sure you can potentially upgrade:

1. Check inside Jira administration panel if your installed plugins are all upwards compatible. Jira has a very good feedback system where you can see if you plugin provider is compatible to the new Jira version.
2. Check or ask inside this repository if anyone has tested the latest image. I have experienced issues when Jira has upgraded to a new major version: E.g. 6.x to 7.x. In this case sometimes the image has to be adapted. Minor versions and especially bugfix version can be usually be used without any problems.

Now make a `Backup` in order to be able to Fallback:

1. Stop your database and Jira instance.
2. Make a backup of your volumes. (Both Jira and database). For example use blacklabelops/volumerize to backup your volume.

Now `Upgrade` your Jira container:

1. Remove your stopped Jira container: `docker rm your_jira_container_name`
2. Upgrade your local image: `docker pull blacklabelops/jira:new_version`
3. Use the same start command as the last container but with the new image `blacklabelops/jira:new_version`
4. Jira will start its upgrading routine on both the local files and database. Run `docker logs -f your_jira_container_name` and lookout for error messages.

Now `Test` your Jira instance:

1. Login and check your functionality
2. Check if all plugins are running
3. Check Jira administration pannel for error messages

Test okay?

Your finished!

Test not okay?

Rollback:

1. Stop Jira and database instance.
2. Play back your backup. E.g. delete volumes, create volumes and copy back old files. Both Jira and database! You can simplify things with blacklabelops/volumerize.
3.  Remove your stopped Jira container: `docker rm your_jira_container_name`
4. Use the same start command as the last container but with the old image `blacklabelops/jira:old_version`

**Comment by esciara** [comment]
Thanks for the detailed version @blacklabelops !

A few questions:

1. You mention having experienced sometimes issues when upgrading to new major versions (e.g. 6.x to 7.x.) and that in this case the image has to be adapted. What do you mean by "adapted"? That an upgrade has to be made within the container image first on the lower version image (6.x in the example) before doing the routine again?
2. You wrote that "Jira will start its upgrading routine on both the local files and database". Would you have some links/references explaining what it does exactly, so to understand what happen under the hood better?
3. Would it be interesting to add this process in the READ.me file?

**Comment by blacklabelops** [comment]
Answer to 1.:

Atlassian can introduce image breaking changes inside major releases. Jira 7 introduced a new installer and a packaged Java version. I had to remove java from the image and had to handle to automate the installation with the new installer.

Confluence 6 introduced collaborative editing of articles. The new symphony framework required an additional port and had some minor issues which hab been resolved in some later releases.

All image environment variable are accompanied by script logic. When Atlassian changes config files there is a high possibility that I also have to change the script logic.

Answer to 2.:

Sorry, can't help you. I just know that routines add new configuration entries to config files and up-to-date java applications use database tools which recognize the database schema version and bring them up-to-date. This is neat and not all applications offer this kind of updates. That's why Atlassian software in general works so well inside Docker images.

Answer to 3.:

Yeah why not, after some editorial work.

**Comment by esciara** [comment]
Thanks @blacklabelops !

Regarding 1. : I understand that the scripts and container need to be updated due to new needs and features being added and needing Dockerfile and scripts upgrade. My question was more about being able or not to simply switch containers and have the upgrade fully done without the need to mutate the container. You mention that the database upgrades itself when it detects a difference of version. It is the same for the other parts of Jira that need upgrading? Your answer to 2. suggests that you might now know that level of details... Right?

**Comment by blacklabelops** [comment]
What do you mean with "mutate the container". When your upgrading to a new image version that's already mutating.
Yes, Jira touches and upgrades the database when it starts. What other parts are upgraded with what kind of procedure I absolutely do not know.

**Comment by blacklabelops** [comment]
Done! Added guide to readme!

**Comment by esciara** [comment]
Didn't say thank you !! :)
