### ISSUE TITLE
Wrong JVM version! You are running with .. but JIRA requires at least 1.8 to run

### ISSUE THREAD

**Issue by Whax** [blacklabelops/jira#86]
Hello,

when i using your image locally with docker-compose on my arch linux i've got no problem but when I use it on my server (alpine 3.7) i've got the following message : 

`Wrong JVM version! You are running with .. but JIRA requires at least 1.8 to run.  `

Any idea ?

Thanks for support.

**Comment by Firefishy** [comment]
What image and tag are you using?

**Comment by Whax** [comment]
image: blacklabelops/jira:latest

**Comment by Firefishy** [comment]
I suspect you may have something wrong with your volume mapping, using an old image or similar. 

`blacklabelops/jira:latest` `sha256:c5d27640784c7b2c77b99dc5daf53c7832b83009a0020285338dae2296bb939c` uses the version of java bundled with JIRA - `Java(TM) SE Runtime Environment (build 1.8.0_102-b14)`

**Comment by Firefishy** [comment]
Check the output of: `docker run blacklabelops/jira:latest /opt/jira/jre/bin/java -version` or similar command using `docker-compose run`

**Comment by Whax** [comment]
I deleted all my images / containers performed a reboot and ran

`docker run blacklabelops/jira:latest /opt/jira/jre/bin/java -version`

~/jira$ docker run blacklabelops/jira:latest /opt/jira/jre/bin/java -version
Unable to find image 'blacklabelops/jira:latest' locally
latest: Pulling from blacklabelops/jira
ff3a5c916c92: Pull complete 
dd1ef7c221e1: Pull complete 
116a5e4f2b81: Pull complete 
ef904d1aeba7: Pull complete 
6eb603bd74b5: Pull complete 
4c47382d05c2: Pull complete 
Digest: sha256:fcc60d85befb0db0c781f81d20df1a069af8d3a8860c6d09cac5f83824bbf597
Status: Downloaded newer image for blacklabelops/jira:latest
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 2555904 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /var/atlassian/jira/hs_err_pid7.log
Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x0000678769000000, 2555904, 1) failed; error='Operation not permitted' (errno=1)

If I bind port
`docker run blacklabelops/jira:latest -p 5900:8080 /opt/jira/jre/bin/java -version`
I've got the first error

I'm using Docker version 18.03.0-ce, build a667b79d1b

**Comment by Firefishy** [comment]
Port bind needs to come before image and looks like you have some memory limits or constrained memory.

**Comment by blacklabelops** [comment]
I have checked the scripts. If you start the container a command starting with `-` then jira will be started with parameters. In this case `-p 5900:8080 /opt/jira/jre/bin/java -version`. Which leads to weird results. 

The only correct way to execute the java command is: `docker run --rm blacklabelops/jira:latest /opt/jira/jre/bin/java -version`.

All in all the main problem seems to be the jvm and your host. I would like to verify, if this problem is a compatibility problem. There is also alpine 3.7 with glibc inside the image.

In order to get a more detailed impression please check the following:

* Run Alpine Open Java RE on your server: `docker run --rm blacklabelops/java:openjre.8 java -version`
* Run Oracle Java on Ubuntu on your server: `docker run --rm blacklabelops/java:ubuntu.jre.8.162 java -version`

This should verify if Java has a general issue on your server or can be limited to java or os inside the image!

**Comment by Whax** [comment]
Hi,

thanks for your both replies and your interest on my problem.

Finally I found the solution :)

I use Alpine 3.7 with a grsec kernel. I had to enable PaX soft mode.

`sysctl -w kernel.pax.softmode=1`
