### ISSUE TITLE
Automatically pull Jira version info?

### ISSUE THREAD

**Issue by jhult** [blacklabelops/jira#91]
Does it make sense to automatically build from the latest version info from the Atlassian website?

These feeds could be used:
- https://my.atlassian.com/download/feeds/current/jira-core.json
- https://my.atlassian.com/download/feeds/current/jira-software.json
- https://my.atlassian.com/download/feeds/current/jira-servicedesk.json

**Comment by blacklabelops** [comment]
Does not make sense. There are no suitable integration tests in place.

**Comment by jhult** [comment]
Here is how others are doing it (just as an FYI): https://github.com/cptactionhank/docker-atlassian-jira

I'm not saying we should or should not implement this. Just posing the question for discussion.

**Comment by jhult** [comment]
Additional feeds (such as RSS) can be found here: https://developer.atlassian.com/server/framework/atlassian-sdk/early-access-programs/

**Comment by blacklabelops** [comment]
Then we also need someone being able to maintain those integration tests.

**Comment by esciara** [comment]
If I can share my point of view/experience: this community is nicely active (greatly thanks to @blacklabelops !) because they participate to upgrades. They do so because there is no automation. Just look at what happened on cptactionhank's images: the integration tests have not been working for a while, and no one stepped in for a long time (not sure whether someone has yet) to fix it, because of lack of involvement.

Hence I would argue: don't automate !!! A keep the community interacting.

My 2 cents/pence.

**Comment by blacklabelops** [comment]
Interaction and participation makes this repository great. I would love to see more discussion and people interacting and contributing.

If anyone contributes to automation, that's wonderful. My hands are full, everybody is welcome to contribute.
